pool:
  vmImage: 'windows-2019'
  demands: npm

steps:
- task: Npm@0
  displayName: 'Install npm packages'
  inputs:
    command: 'ci'

- task: Npm@0
  displayName: Run production build
  condition: eq(variables.env, 'production')
  inputs:
    command: run
    arguments: 'build-prod'

- task: Npm@0
  displayName: Run stage build
  condition: eq(variables.env, 'stage')
  inputs:
    command: run
    arguments: 'build-stage'

- task: DeleteFiles@1
  displayName: 'Delete web.config files from translated folders'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/dist'
    Contents: |
      hr/web.config

- task: ArchiveFiles@1
  displayName: 'Archive files '
  inputs:
    rootFolder: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false

- task: CopyFiles@2
  displayName: 'Copy File to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '$(Build.BuildId).zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
